apiVersion: v1
kind: Service
metadata:
  name: {{ include "wakapi.fullname" . }}
  labels:
    {{- include "wakapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ include "wakapi.name" . }}