image:
    repository: ENC[AES256_GCM,data:WU7f6mwE4HTCEg1rTNMyO3fnTgY73A==,iv:+haCuA45W20pI5dfzYke8PZnpLrb0bZeNYe+udVI/kE=,tag:5sZC9R7hAw7mfAgGX0cLBQ==,type:str]
secret:
    enabled: ENC[AES256_GCM,data:M2OvrA==,iv:SUyinS/YqEPSvUCWo6q+dkB1uWrpQEUw8uvNOOm/5w0=,tag:4rtFszm11sAiIy9K6k9sqQ==,type:bool]
    name: ENC[AES256_GCM,data:F1wqFVlg,iv:fQEGk91JC1JMDBPj2JXpxGXyxK2yJzpsj9RPmwz7BAU=,tag:M33yXFWAwj80me6idBCiPA==,type:str]
    data:
        WAKAPI_PASSWORD_SALT: ENC[AES256_GCM,data:JJqG9Gq0dCCyafsPAMRj74aVTtT3g1Y6ZHznR7wqzvg=,iv:y0BiRoNeqzCtUHGB9ahl7uePZs6QSFW5f4SmRXKbBcY=,tag:rq/XtuDiZ9QcihWJIzyPFQ==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:ti+3d4FDMFsy2OuEjUSSBI6p,iv:PhgUadY+GQaBlW8fbV5OVfY+9uPfKCkvnpfnB447HL0=,tag:Q/0xjpcFYQo4UWahe8qu5g==,type:str]
        WAKAPI_DB_DSN: ENC[AES256_GCM,data:GNQkpFzKRsJc8whRtEv62PzIiosPdxuOKtNeh16vxN3XM/H2PQDClkOVl9ba/IaCZ06oik6mpdfxs91F4BIONJOQ7+dGorTQlnT1wKu1WImMUQ4B1Oc7wO1Zd7U58B8=,iv:miJdIp1cQyRs2gAslXEmkOU4T2bTRPpqNBcyptgTUqc=,tag:OeE8XI2D+cXls9tjc4adwA==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:IvUBsA==,iv:2SqQLbNp6HeD2tRfejmE1Nn2XLQz3MdUdP902X3PdMU=,tag:ejIajBZqeGqJ/yjnMfHRSg==,type:bool]
    className: ENC[AES256_GCM,data:mIcWqCE=,iv:xq7n1uhmPeQKiWrpcGx+faVLJSfDEwVRKGu2s4WXCIM=,tag:+uv6KxPXnSziLrCiJmp96g==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:M2ILdCfyVVMsCwsO,iv:kxRLU3E9U3di0Atb+stcwXN5ab1bBaTAiVIAhXl7xrU=,tag:eu5s3LiVb9QW1K8jchhQjA==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:p9R2JNerYZAv0YJeD33ItCXb,iv:5aApQEQnWxFL9RU6pzF/RMdlh4wRhXdgSSJ0NPybiQw=,tag:tsevEYOkB6EVN1fJqSHGsw==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Ww==,iv:+SptLwL5eqQd7RsmPC/Ta3mO/0eaCW3NUUoFhjSeuGk=,tag:JAcKcjIzM5mFw2FU2OYaeQ==,type:str]
              pathType: ENC[AES256_GCM,data:Nu6Fjd1KvfrHPt9v6GKYw2c2F0F+hA==,iv:ZtdUHvf+QxxUm9xhuWos/mgMAuoP2n5dDXFSlhgcAuw=,tag:urVorroao35VucBKHna+Gg==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:iWimZzadxvXilxkb9mK0AlR2OUUM6xpGNaPMPRtzbEVOdJoWJTXRlw==,iv:TR1O4Es1MIOBxNrSCNaFdNRLSg5q95hTYGVApSMEIJg=,tag:8KDribpLiDbj3pJM70Ouyw==,type:comment]
            - ENC[AES256_GCM,data:iT73G+252nWCoun0s0TCCwNY,iv:ejpVttdDhy9tZ13v4d7n5xxmnRcc9iuOxordEeI2dr0=,tag:4hG0T3xR0bzODgCLb3m16Q==,type:str]
          secretName: ENC[AES256_GCM,data:sGU6RPEIIvIQk2BEsn+yvdycmFUeFg==,iv:86/H0c7INaDM1GTYKha+C/PmJ/zR+75VhKcSdq2W3YM=,tag:Fqbr1+Mcn7j11DsFTGSsEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-09-16T18:25:18Z"
    mac: ENC[AES256_GCM,data:jVdEbQK15fEZX91ws3N8q6PAc/nmUDL6dRGxol7ThiHzD6x6SdhxpUu21on06NTWI+qFRIwKZhiL0p4jruv9wjb7b+q5ZSf7Zo4deykyYXG7c9gDWTV225SQSQg1LQ33VE760h5dDNuJc8ARbcaWpej6LHjcpqEK6HnwqxXS5gQ=,iv:DM1J+ZEy93UOmIQvVrG4yiB/BT4slKxtdMju0YzPTFk=,tag:kqrQObMBwuy0IuTcsjz31A==,type:str]
    pgp:
        - created_at: "2024-09-16T18:25:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DsnNQZ3UzqQcSAQdAPaJglxRV5hFIXxDNRsEuedDXu5ndY4IOGOW148e7Nyow
            edd4dwpMeqBSNqc4QDR74Ges+hu4FzW7bg+S5Z2iC275QVZPESuuccgXPO/gDk2g
            1FsBCQIQxLSXu0V9RqFZsUkniwLOgJ2W+8zRo2iMBudQgdtBNyg2R8MZbJntHT+O
            J1LEHg/U2Gb2FjLp3OiGHbKfhKDubjcADVOPzqmYbFUOgGO+6vqvrRRQiIP0
            =mypT
            -----END PGP MESSAGE-----
          fp: 27D207A8D450CBA4CE9BD75552F3A995CBB43450
    unencrypted_suffix: _unencrypted
    version: 3.9.0
