replicaCount: 1

image:
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

volume:
  enabled: true
  name: "wakapi-data-volume"
  mountPath: "/data"
  storageClass: ""  # Оставьте пустым, если не используете StorageClass
  accessMode: ReadWriteOnce
  size: 5Gi

config:
  enabled: true
  data:
#    db_host: "postgresql.production.svc.cluster.local"         # Порт сервера Wakapi
    db_host: "postgresql"         # Порт сервера Wakapi
    db_port: "5432"
    db_user: "wakapi"
    db_name: "wakapi"
    db_type: "postgres"

resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }