replicaCount: 1

image:
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

volume:
  enabled: true
  name: "wakapi-data-volume"
  mountPath: "/data"
  storageClass: ""  # Оставьте пустым, если не используете StorageClass
  accessMode: ReadWriteOnce
  size: 5Gi

exporter:
  enabled: true
  image:
    repository: "macropower/wakatime-exporter"
    tag: "latest"
    pullPolicy: IfNotPresent
  wakapi:
    host: "http://wakapi:3000/api"  # Здесь указываем адрес Wakapi (внутренний DNS)
  service:
    type: ClusterIP
    port: 9212
  resources: {}

resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }